### ISSUE TITLE
User story: Game library page

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/Boardwalk-Games#8]
**User story:** 
As a user, I would like to see a collection of new and classic games to choose from

**Acceptance Criteria**

- [x] Must show 4 new games and 4 old games
- [x] Must include images

**Tasks**

- [x] Create, in a card format, these new and classic games, separating them by category
- [x] Add information including title, image, description, number of players and age range
- [x] Ensure a responsive design layout for all devices
