### ISSUE TITLE
User Story: Game booking form

### ISSUE THREAD

**Issue by JamesBracken** [JamesBracken/Boardwalk-Games#9]
**User story:**
As a user I would like to be able to fill out a form to reserve a game on any
given day

**Acceptance Criteria** 

- [x] Must have a short form to reserve one game on a specific day 
- [x] Must have a success page following submitting a filled form

**Tasks**

- [x] Create a form fillout section to reserve a game
- [x] Make form responsive on all devices
- [x] Create a success page following the form
